(function () {
  window.GAPPS = {
    APPS: [
      { key: 'mail', name: 'Gmail', desc: 'Email',
        url: 'https://mail.google.com/', learnMore: 'https://workspace.google.com/products/gmail/',
        shortcutHost: 'mail', categories: ['communication'] },
      { key: 'calendar', name: 'Calendar', desc: 'Calendars',
        url: 'https://calendar.google.com/', learnMore: 'https://workspace.google.com/products/calendar/',
        categories: ['communication'] },
      { key: 'keep', name: 'Keep', desc: 'Digital notes',
        url: 'https://keep.google.com/', learnMore: 'https://workspace.google.com/products/keep/',
        categories: ['productivity'] },
      { key: 'tasks', name: 'Tasks', desc: 'Tasks and task lists',
        url: 'https://tasks.google.com/', learnMore: 'https://workspace.google.com/products/tasks/',
        categories: ['productivity'] },
      { key: 'contacts', name: 'Contacts', desc: 'Address book',
        url: 'https://contacts.google.com/', categories: ['communication'] },
      { key: 'voice', name: 'Voice', desc: 'Phone and voicemail',
        url: 'https://voice.google.com/', learnMore: 'https://workspace.google.com/products/voice/',
        categories: ['communication'] },
      { key: 'meet', name: 'Meet', desc: 'Video conferencing',
        url: 'https://meet.google.com/', learnMore: 'https://workspace.google.com/products/meet/',
        categories: ['communication'] },
      { key: 'chat', name: 'Chat', desc: 'Messaging and conversations',
        url: 'https://chat.google.com/', learnMore: 'https://workspace.google.com/products/chat/',
        categories: ['communication'] },
      { key: 'groups', name: 'Groups', desc: 'Mailing lists & forums',
        url: 'https://groups.google.com/', categories: ['communication'] },
      { key: 'account', name: 'Account', desc: 'Manage your Google Account',
        url: 'https://myaccount.google.com/', shortcutHost: 'myaccount',
        categories: ['utilities'] },
      { key: 'search', name: 'Search', desc: 'Web search',
        url: 'https://www.google.com/', categories: ['utilities'] },
      { key: 'gemini', name: 'Gemini', desc: 'AI assistant',
        url: 'https://gemini.google.com/', learnMore: 'https://workspace.google.com/products/gemini/',
        categories: ['productivity'] },
      { key: 'photos', name: 'Photos', desc: 'Photo storage and sharing',
        url: 'https://photos.google.com/', categories: ['utilities'] },
      { key: 'drive', name: 'Drive', desc: 'Cloud storage',
        url: 'https://drive.google.com/', learnMore: 'https://workspace.google.com/products/drive/',
        categories: ['productivity'] },
      { key: 'docs', name: 'Docs', desc: 'Word processing',
        url: 'https://docs.google.com/', learnMore: 'https://workspace.google.com/products/docs/',
        categories: ['productivity'] },
      { key: 'sheets', name: 'Sheets', desc: 'Spreadsheets',
        url: 'https://sheets.google.com/', learnMore: 'https://workspace.google.com/products/sheets/',
        categories: ['productivity'] },
      { key: 'slides', name: 'Slides', desc: 'Presentation builder',
        url: 'https://slides.google.com/', learnMore: 'https://workspace.google.com/products/slides/',
        categories: ['productivity'] },
      { key: 'vids', name: 'Vids', desc: 'Video editor',
        url: 'https://vids.google.com/', learnMore: 'https://workspace.google.com/products/vids/',
        categories: ['productivity'] },
      { key: 'forms', name: 'Forms', desc: 'Online forms and surveys',
        url: 'https://forms.google.com/', learnMore: 'https://workspace.google.com/products/forms/',
        categories: ['productivity'] },
      { key: 'sites', name: 'Sites', desc: 'Create and host websites',
        url: 'https://sites.google.com/', learnMore: 'https://workspace.google.com/products/sites/',
        categories: ['productivity'] },
      { key: 'passwords', name: 'Passwords', desc: 'Password manager',
        url: 'https://passwords.google.com/', categories: ['utilities'] },
      { key: 'maps', name: 'Maps', desc: 'Maps and directions',
        url: 'https://maps.google.com/', learnMore: 'https://maps.google.com/',
        categories: ['utilities'] },
      { key: 'translate', name: 'Translate', desc: 'Translation',
        url: 'https://translate.google.com/', learnMore: 'https://translate.google.com/',
        categories: ['utilities'] },
      { key: 'saved', name: 'Saved', desc: 'Places and items you saved',
        url: 'https://www.google.com/save/', categories: ['utilities'] },
      { key: 'one', name: 'Google One', desc: 'Premium storage plan',
        url: 'https://one.google.com/', categories: ['utilities'] },
      { key: 'youtube', name: 'YouTube', desc: 'Video sharing',
        url: 'https://www.youtube.com/', learnMore: 'https://www.youtube.com/',
        categories: ['entertainment'] },
      { key: 'ytmusic', name: 'YouTube Music', desc: 'Music streaming',
        url: 'https://music.youtube.com/', learnMore: 'https://music.youtube.com/',
        categories: ['entertainment'] },
      { key: 'play', name: 'Play', desc: 'Apps, games, and media',
        url: 'https://play.google.com/', learnMore: 'https://play.google.com/',
        categories: ['entertainment'] },
      { key: 'news', name: 'News', desc: 'Personalized news',
        url: 'https://news.google.com/', learnMore: 'https://news.google.com/',
        categories: ['entertainment'] },
      { key: 'finance', name: 'Finance', desc: 'Markets and portfolios',
        url: 'https://www.google.com/finance/', learnMore: 'https://www.google.com/finance/',
        categories: ['entertainment'] },
      { key: 'earth', name: 'Earth', desc: '3D globe explorer',
        url: 'https://earth.google.com/', learnMore: 'https://earth.google.com/',
        categories: ['entertainment'] },
      { key: 'arts', name: 'Arts & Culture', desc: 'Museum collections online',
        url: 'https://artsandculture.google.com/', learnMore: 'https://artsandculture.google.com/',
        categories: ['entertainment'] },
      { key: 'wallet', name: 'Wallet', desc: 'Cards and passes',
        url: 'https://wallet.google.com/', categories: ['commerce'] },
      { key: 'shopping', name: 'Shopping', desc: 'Find and buy products',
        url: 'https://shopping.google.com/', learnMore: 'https://shopping.google.com/',
        categories: ['commerce'] },
      { key: 'travel', name: 'Travel', desc: 'Trip planning',
        url: 'https://www.google.com/travel/', categories: ['commerce'] },
      { key: 'books', name: 'Books', desc: 'Books library',
        url: 'https://books.google.com/', categories: ['entertainment'] },
      { key: 'store', name: 'Store', desc: 'Google hardware store',
        url: 'https://store.google.com/', learnMore: 'https://store.google.com/',
        categories: ['commerce'] },
      { key: 'notebooklm', name: 'NotebookLM', desc: 'AI research assistant',
        url: 'https://notebooklm.google.com/', learnMore: 'https://workspace.google.com/products/notebooklm/',
        categories: ['productivity'] },
      { key: 'blogger', name: 'Blogger', desc: 'Blog publishing',
        url: 'https://www.blogger.com/', categories: ['business'] },
      { key: 'business', name: 'Business Profile', desc: 'Manage business information',
        url: 'https://www.google.com/business/', categories: ['business'] },
      { key: 'analytics', name: 'Analytics', desc: 'Web and app analytics',
        url: 'https://analytics.google.com/', learnMore: 'https://workspace.google.com/products/google-analytics/',
        categories: ['business'] },
      { key: 'adcenter', name: 'My Ad Center', desc: 'Ad preferences',
        url: 'https://myadcenter.google.com/', categories: ['business'] },
      { key: 'merchant', name: 'Merchant Center', desc: 'Product listings',
        url: 'https://merchants.google.com/', learnMore: 'https://workspace.google.com/products/merchant-center/',
        categories: ['business'] },
      { key: 'ads', name: 'Google Ads', desc: 'Online advertising',
        url: 'https://ads.google.com/', learnMore: 'https://workspace.google.com/products/google-ads/',
        categories: ['business'] },
      { key: 'fi', name: 'Google Fi', desc: 'Mobile phone service',
        url: 'https://fi.google.com/', categories: ['commerce'] },
      { key: 'admin', name: 'Admin', desc: 'Workspace admin console',
        url: 'https://admin.google.com/', learnMore: 'https://workspace.google.com/products/admin/',
        categories: ['workspace'] },
      { key: 'vault', name: 'Vault', desc: 'eDiscovery and retention',
        url: 'https://vault.google.com/', learnMore: 'https://workspace.google.com/products/vault/',
        categories: ['workspace'] },
      { key: 'cloudsearch', name: 'Cloud Search', desc: 'Search across Workspace',
        url: 'https://cloudsearch.google.com/', learnMore: 'https://workspace.google.com/products/cloud-search/',
        categories: ['workspace'] },
      { key: 'classroom', name: 'Classroom', desc: 'Education tools',
        url: 'https://classroom.google.com/', learnMore: 'https://workspace.google.com/products/classroom/',
        categories: ['workspace'] }
    ],

    ORDERS: {
      category: null,  // null means use APPS array order (logical/category order)
      popularity: [
        'search', 'youtube', 'maps', 'mail', 'photos', 'drive', 'play',
        'calendar', 'docs', 'meet', 'translate', 'sheets', 'news', 'gemini', 'account',
        'chat', 'contacts', 'passwords', 'shopping', 'wallet', 'keep', 'tasks', 'ytmusic',
        'finance', 'slides', 'travel', 'forms', 'saved', 'earth', 'voice', 'books', 'arts',
        'classroom', 'store', 'sites', 'notebooklm', 'one', 'groups', 'vids',
        'fi', 'blogger', 'business', 'analytics', 'ads', 'adcenter', 'merchant', 'admin',
        'vault', 'cloudsearch'
      ],
      shadologiq: [
        'search', 'mail', 'youtube', 'maps', 'photos', 'calendar', 'drive',
        'docs', 'meet', 'chat', 'contacts', 'passwords', 'account', 'sheets', 'keep',
        'tasks', 'translate', 'play', 'wallet', 'gemini', 'one', 'ytmusic', 'news',
        'shopping', 'finance', 'travel', 'saved', 'slides', 'forms', 'notebooklm',
        'earth', 'books', 'arts', 'sites', 'voice', 'vids', 'groups', 'store', 'classroom',
        'fi', 'blogger', 'business', 'analytics', 'ads', 'adcenter',
        'merchant', 'admin', 'vault', 'cloudsearch'
      ]
    },

    LISTS: {
      gmail: ['mail', 'calendar', 'contacts', 'meet', 'chat', 'account', 'search', 'gemini', 'photos', 'drive', 'docs', 'sheets', 'slides', 'forms', 'keep', 'tasks', 'maps', 'translate', 'saved', 'youtube', 'ytmusic', 'play', 'news', 'finance', 'earth', 'arts', 'wallet', 'shopping', 'books'],
      'ws-legacy': ['mail', 'calendar', 'keep', 'tasks', 'contacts', 'voice', 'meet', 'chat', 'groups', 'account', 'search', 'gemini', 'photos', 'drive', 'docs', 'sheets', 'slides', 'vids', 'forms', 'sites', 'passwords', 'maps', 'translate', 'saved', 'youtube', 'play', 'news', 'finance', 'earth', 'wallet', 'shopping', 'travel', 'books', 'store', 'blogger', 'admin'],
      'ws-starter': ['mail', 'calendar', 'contacts', 'voice', 'meet', 'chat', 'groups', 'account', 'search', 'gemini', 'photos', 'drive', 'docs', 'sheets', 'slides', 'forms', 'sites', 'keep', 'tasks', 'maps', 'translate', 'youtube', 'ytmusic', 'play', 'news', 'finance', 'admin', 'one', 'notebooklm'],
      'ws-standard': ['mail', 'calendar', 'contacts', 'voice', 'meet', 'chat', 'groups', 'account', 'search', 'gemini', 'photos', 'drive', 'docs', 'sheets', 'slides', 'vids', 'forms', 'sites', 'keep', 'tasks', 'maps', 'translate', 'youtube', 'ytmusic', 'play', 'news', 'finance', 'admin', 'one', 'cloudsearch', 'notebooklm'],
      'ws-plus': ['mail', 'calendar', 'contacts', 'voice', 'meet', 'chat', 'groups', 'account', 'search', 'gemini', 'photos', 'drive', 'docs', 'sheets', 'slides', 'vids', 'forms', 'sites', 'keep', 'tasks', 'maps', 'translate', 'youtube', 'ytmusic', 'play', 'news', 'finance', 'admin', 'one', 'vault', 'cloudsearch', 'notebooklm'],
      'ws-enterprise': ['mail', 'calendar', 'contacts', 'voice', 'meet', 'chat', 'groups', 'account', 'search', 'gemini', 'photos', 'drive', 'docs', 'sheets', 'slides', 'vids', 'forms', 'sites', 'keep', 'tasks', 'books', 'maps', 'translate', 'youtube', 'ytmusic', 'play', 'news', 'finance', 'admin', 'one', 'vault', 'cloudsearch', 'notebooklm'],
      'ws-education': ['mail', 'calendar', 'classroom', 'groups', 'contacts', 'voice', 'meet', 'chat', 'account', 'search', 'gemini', 'photos', 'drive', 'docs', 'sheets', 'slides', 'forms', 'sites', 'keep', 'tasks', 'maps', 'translate', 'youtube', 'ytmusic', 'play', 'news', 'finance', 'admin', 'vault', 'notebooklm'],
      'ws-essentials': ['mail', 'calendar', 'contacts', 'meet', 'chat', 'groups', 'account', 'search', 'gemini', 'photos', 'drive', 'docs', 'sheets', 'slides', 'vids', 'forms', 'sites', 'keep', 'tasks', 'maps', 'translate', 'youtube', 'ytmusic', 'play', 'news', 'finance', 'admin', 'notebooklm']
    },

    CATEGORIES: [
      { slug: 'communication', label: 'Communication' },
      { slug: 'productivity', label: 'Productivity' },
      { slug: 'utilities', label: 'Utilities' },
      { slug: 'entertainment', label: 'Entertainment & Media' },
      { slug: 'commerce', label: 'Commerce & Travel' },
      { slug: 'business', label: 'Business & Creation' },
      { slug: 'workspace', label: 'Workspace Admin' }
    ]
  };
})();
